### ISSUE TITLE
"Weird" search live completion result order?

### ISSUE THREAD

**Issue by hartwork** [karlb/wikdict-web#8]
When switching to Spanish+English and typing "gato" (for animal cat in Spanish), I see this:

![gato](https://user-images.githubusercontent.com/1577132/140993061-7de337fa-abe8-4f7c-978b-2619c4eaf8f2.png)

What's surprising here is that:
- Sort seems case sensitive without intention (but that's a guess)
- Longer words appear before shorter words, while sharing identical prefix.

Is that known and intended?

**Comment by karlb** [comment]
This is not intended. The scoring used here is `max_score * rel_importance` but `rel_importance` is null, thereby throwing off the whole sorting algorithm. It works much better when is use `max_score * coalesce(rel_importance, 0.01)`, but I want to check whether rel_importance is allowed to be null at all and remind myself of the exact meaning of these variables before pushing a fix.

I assume https://github.com/karlb/wikdict-web/issues/9 has the same underlying reason.

**Comment by hartwork** [comment]
> This is not intended.

Okay, nice.

> [..] and remind myself of the exact meaning of these variables before pushing a fix.

Looking forward to that.

> I assume #9 has the same underlying reason.

I have a feeling that there is a hardcoded limit saying "words of length 3 are too short" as well. True?
Though maybe that's off-topic here :shrug:

**Comment by karlb** [comment]
> I have a feeling that there is a hardcoded limit saying "words of length 3 are too short" as well. True?

Three letters should be sufficient, but words shorter than that won't get completed. After three letters, a completion list for words starting with these letters is fetched and used as the user continues typing. This reduces latency while typing and is more cacheable than doing a request after each letter.

**Comment by hartwork** [comment]
With 3bd80b5ac116aa4bf761e3d04bbcf1a84c240473 applied I get this:

![gato2](https://user-images.githubusercontent.com/1577132/141685981-8b7547fb-5c7b-403b-8173-99151d978947.png)

Cool! :tada:  Any chance you could re-deploy production from `master`?

**Comment by karlb** [comment]
> Cool! tada Any chance you could re-deploy production from master?

Done, see also [today's blog post](https://blog.wikdict.com/2021/11/new-results-page-inflections-wikdict.html).

**Comment by hartwork** [comment]
@karlb https://www.wikdict.com/en-es/ is still putting "gato" after "Gato Risón", even after forced reload. Am I missing something?

**Comment by hartwork** [comment]
Chromium seems fine, but it's still broken in Firefox. Turns out that the https://www.wikdict.com/typeahead/en-es/gat response is cached, will only expire ~30 minutes from now, and forced reload is being ignored on that resource. Oh my :smiley: So I guess it will work fine from 16:00 UTC+1 then…

**Comment by hartwork** [comment]
> So I guess it will work fine from 16:00 UTC+1 then…

Works in Firefox now as expected :+1:
